reviewmanager_configuration_form:
  path: /reviewmanager/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Reviewmanager\Controller\ReviewmanagerConfigurationController::index'
    # Needed to work with tab system
    _legacy_controller: AdminReviewmanager
    _legacy_link: AdminReviewmanager