services:
  _defaults:
    public: true

  # Reviewmanager configuration text form
  reviewmanager.form.type.reviewmanager_configuration_text:
    class: 'Reviewmanager\Form\ReviewmanagerConfigurationFormType'
    parent: 'form.type.translatable.aware'
    public: true
    tags:
      - { name: form.type }

  reviewmanager.form.reviewmanager_configuration_text_data_configuration:
    class: Reviewmanager\Form\ReviewmanagerConfigurationTextDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']

  reviewmanager.form.reviewmanager_configuration_text_form_data_provider:
    class: 'Reviewmanager\Form\ReviewmanagerConfigurationTextFormDataProvider'
    arguments:
      - '@reviewmanager.form.reviewmanager_configuration_text_data_configuration'

  reviewmanager.form.reviewmanager_configuration_text_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@reviewmanager.form.reviewmanager_configuration_text_form_data_provider'
      - 'Reviewmanager\Form\ReviewmanagerConfigurationFormType'
      - 'ReviewmanagerConfiguration'