services:

  # Reviewmanager configuration form
  reviewmanager.form.type.reviewmanager_configuration:
    class: 'Reviewmanager\Form\ReviewmanagerConfigurationFormType'
    parent: 'form.type.translatable.aware'
    tags:
      - { name: form.type }

  reviewmanager.form.reviewmanager_configuration_data_configuration:
    class: Reviewmanager\Form\ReviewmanagerConfigurationDataConfiguration
    arguments: ['@prestashop.adapter.legacy.configuration']

  reviewmanager.form.reviewmanager_configuration_form_data_provider:
    class: 'Reviewmanager\Form\ReviewmanagerConfigurationFormDataProvider'
    arguments:
      - '@reviewmanager.form.reviewmanager_configuration_data_configuration'

  reviewmanager.form.reviewmanager_configuration_form_data_handler:
    class: 'PrestaShop\PrestaShop\Core\Form\Handler'
    arguments:
      - '@form.factory'
      - '@prestashop.core.hook.dispatcher'
      - '@reviewmanager.form.reviewmanager_configuration_form_data_provider'
      - 'Reviewmanager\Form\ReviewmanagerConfigurationFormType'
      - 'ReviewmanagerConfiguration'

  ReviewmanagerConfigurationController:
    class: Reviewmanager\Controller\ReviewmanagerConfigurationController
